title: Geef de waarde van een variabele weer met TextMeshPro
hero_image: images/banner.png
description: Geef de waarde van een variabele weer met een TextMeshPro UI GameObject
version: 4
listed: false
copyedit: false
last_tested: "2021-11-18"
steps:
  - 
    title: Geef de waarde van een variabele weer met TextMeshPro
